sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- "10.15.1"
before_install:
  - # start your web application and listen on `localhost`
  - # google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - # npm install -g @angular/cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run test:ci
  - ng build --prod
before_deploy: "echo 'ready?'"
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: develop
    project: "accet97-dev"
    message: "deployment to dev environment"
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master
    project: "accet97-stage"
    message: "deployment to stage environment"