language: node_js
node_js:
- "10.15.1"
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_deploy: "echo 'ready?'"
deploy:
  - provider: firebase
    skip_cleanup: true
    before_script:
      - npm install -g @angular/cli
    script:
      - npm install
      - ng build --prod
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: develop
    project: "accet97-dev"
    message: "deployment to dev environment"
  - provider: firebase
    skip_cleanup: true
    before_script:
      - npm install -g @angular/cli
    script:
      - npm install
      - ng build --prod
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master
    project: "accet97-stage"
    message: "deployment to stage environment"