sudo: required
dist: trusty
addons:
  chrome: stable
  sonarcloud:
    organization: "accet9397"
    token:
      secure: $SONARCLOUD_TOKEN
language: node_js
node_js:
- "10.15.1"
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test:ci
  - sonar-scanner
  - ng build --configuration=development
before_deploy: "echo 'ready?'"
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: develop
    project: "accet97-dev"
    message: "deployment to dev environment"
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master
    project: "accet97-stage"
    message: "deployment to stage environment"
