docker:
  credentialsId: "Prem"
  registry: "hub.docker.com"
  org: "stationsoft"
  image: "station-api"
  tag: "dev"

cloud:
  credentialsId: ""
  host: ""
  project: ""
  dc: ""
  
############################################################################################
# Strategy Options:
#   "DEF-APPR"    - Choose the default environment, but ask for approval to deploy
#   "DEF-NO-APPR" - Choose the default environment, and do not ask for approval to deploy
#   "ASK"         - Ask for the environment to deploy. Ignore default
#   "BYPASS"      - Bypass deployment. Ignore default
############################################################################################
dev:
  phase: "Dev"
  deployment: {strategy: "DEF-NO-APPR", default: "DEV2"}
  environments:
    - "DEV1"
    - "DEV2"
    - "DEV3"
test:
  phase: "Test"
  deployment: {strategy: "DEF-APPR", default: "TEST1"}
  environments:
    - "TEST1"
    - "TEST2"
    - "TEST3"
stage:
  phase: "Stage"
  deployment: {strategy: "ASK", default: "STAGE3"}
  environments:
    # - "STAGE1" Used for triaging production issues
    - "STAGE2"
    - "STAGE3"
prod:
  phase: "Prod"
  deployment: {strategy: "BYPASS", default: "PROD"}
  environments:
    - "PROD"